### PR TITLE
Update all.txt

### PR DESCRIPTION
**Pull request by resolniytlaer**
Change dtw-python to version 1.3.0 to avoid conflicts with numpy   >= 1.2.0
#503

### CODE REVIEW

**Comment by leo19941227** [comment]
Hi @resolniytlaer,

Could you report the DTW results to see whether the version upgrade can still reproduce the results in the SUPERB paper?

**Comment by resolniytlaer** [comment]
What kind of results should I provide then, I got: 

- a xml file 
- two pdfs (TWV, DET) 
- score.out file
- some records of the process

the code however has other bugs, which I suspect was an error of my computer system, because the code pauses and halts (monitored with htop). I simply added two lines of print(" ",end="") to the code in the Processpool executor for loops.

I don't think that this is an issue regarding to dtw-python package(after updated to 1.3.0). Before updating dtw-python, it returns error, and the update was done in the dtw-python repository [(link)](https://github.com/DynamicTimeWarping/dtw-python/commit/7f435a78a929f01a9aa0463af091709a5f207b73) after version 1.1.6

**Comment by resolniytlaer** [comment]
before the dtw-python upgrade (1.1.6 -> 1.3.0) it gives error 
```
File "/home/kk/Desktop/DLHLP/S3PRL/s3prl/s3prl/downstream/quesst14_dtw/expert.py", line 141, in log_records
    query_name, doc_name, score = future.result()
  File "/home/kk/anaconda3/envs/S3PRL/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.get_result()
  File "/home/kk/anaconda3/envs/S3PRL/lib/python3.10/concurrent/futures/_base.py", line 403, in get_result
    raise self._exception
AttributeError: module 'numpy' has no attribute 'int'.
np.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by leo19941227** [comment]
Hi @resolniytlaer ,

Thanks for the information. I mean the MTWV metric which was reported in the original paper. You might use HuBERT or wav2vec2 to run layer-wise experiment and see whether the highest MTWV is closed to the number in the paper.

**Comment by gaeulisautumn** [comment]
@leo19941227 
We have wrote a script to run through the layers. We haven't find the best layer for HuBERT, yet we suspect that the best layer is over 10, as the max TWV curve hasn't fallen. 

```
# layer from 1 -> 10
test (Cnxe)
act:3.1975498 ,m:0.98518604
act:3.206168 ,m:0.9885476
act:3.1910343 ,m:0.98203015
act:3.1854267 ,m:0.9784072
act:3.184873 ,m:0.9776126
act:3.1860702 ,m:0.97814435
act:3.1835973 ,m:0.97583467
act:3.1859145 ,m:0.9765745
act:3.1865366 ,m:0.97624904
act:3.1806855 ,m:0.9727535
dev (Cnxe)
act:3.2118213 ,m:0.98516554
act:3.2198436 ,m:0.9872854
act:3.2061322 ,m:0.98286885
act:3.2002788 ,m:0.9793558
act:3.199511 ,m:0.97890013
act:3.201905 ,m:0.9797231
act:3.2000415 ,m:0.97771716
act:3.2021713 ,m:0.97834796
act:3.2037888 ,m:0.97894484
act:3.196579 ,m:0.97503465
test (TWV)
act:0.020622017 ,m:0.021707457
act:-4.5694405E-4 ,m:0.003027301
act:0.029221956 ,m:0.03381307
act:0.042590905 ,m:0.04521066
act:0.046085622 ,m:0.047838297
act:0.048918974 ,m:0.050104044
act:0.058223695 ,m:0.059633117
act:0.056451805 ,m:0.059938096
act:0.058254804 ,m:0.060283445
act:0.06586559 ,m:0.07285812
dev (TWV)
act:0.008292023 ,m:0.010303854
act:-0.0060749655 ,m:0.0023073028
act:0.015457544 ,m:0.017099114
act:0.023806445 ,m:0.025665618
act:0.031404655 ,m:0.03196205
act:0.027020782 ,m:0.028518258
act:0.039369904 ,m:0.040664423
act:0.03553152 ,m:0.036353942
act:0.034501676 ,m:0.03604897
act:0.045764536 ,m:0.049980417
```

The prediction of the best layer was uploaded to SUPERB and got a score of 7.29 in the QbE section, which is similar to that of HuBERT base, the MTWV was similar too, with 0.0728 against 0.0736. The username of my superb account is gaeulisautumn, and the method is layer10. May I ask what is the best layer, though, as I am tired of testing over and over? I could run other models to check if the results are coherent, given the best layer. On top of that are there any other downstream that utilizes dtw-python? As this update might affect them too. As of my knowledge, there are none, according to the [SUPERB](https://arxiv.org/abs/2105.01051]) paper.

**Comment by leo19941227** [comment]
Hi @gaeulisautumn,

You can refer to here for the best layer of HuBERT:

https://github.com/s3prl/s3prl/blob/main/s3prl/downstream/docs/superb_artifacts.md#qbe

So it is the final layer. You can directly report the MTWV on the test set without the dev set score.
Thanks!

**Comment by gaeulisautumn** [comment]
@leo19941227 
Thanks a lot for pointing out the best layer, the scores are as follows:
```
# wav2vec2
actTWV: 0.018973278  maxTWV: 0.02131649  Threshold: 2.0919
actCnxe: 3.1968715  minCnxe: 0.9844817

# wav2vec2_large
actTWV: 0.04562899  maxTWV: 0.050310712  Threshold: 1.9036
actCnxe: 3.1908731  minCnxe: 0.9790643

# hubert
actTWV: 0.07068498  maxTWV: 0.071938075  Threshold: 1.866
actCnxe: 3.175961  minCnxe: 0.97067875

# hubert_large
actTWV: 0.031906854  maxTWV: 0.034023948  Threshold: 1.9234
actCnxe: 3.190664  minCnxe: 0.98055464
```
The results benchmark.xml files were also uploaded to the SUPERB website as prediction under the username gaeulisautumn and the results of the QbE section were:
||wav2vec2_base|wav2vec2_large|hubert|hubert_large|
|-|-|-|-|-|
|dtw to 1.3.0| 2.13| 5.03| 7.19|3.4 |
|original|2.33 |4.89 |7.36 |3.53|

There were some minor differences

**Comment by leo19941227** [comment]
Thanks @gaeulisautumn , LGTM!

**Comment by gaeulisautumn** [comment]
Hello, although the MTWV results and superb results matches, the best layer accoring to the test set that I found was different in wav2vec. I plan to use the old version of dtw with a modification of the bug(np.int -> int) to check if the results are different. This might take some time though.
